site_name: MkLorum
site_url : https://example.com/
nav:
    - Home: index.md
    - About: about.md
    - Petit Déjeuner: petitdejeuner.md
    - Plats principals: platprincipal.md
    - Desserts: desserts.md
theme: material
